version: "3.1"

services:
  
  db:
    image: mysql:8.0.28
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always

  node:
    build: ./node
    container_name: node-container
    restart: always
    volumes:
      - ./node:/home/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  web:
    build: ./php
    container_name: php-container
    restart: always
    volumes:
      - ./php:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
      - node
      