#!/bin/bash

# Pull the Docker images from DockerHub
docker pull omerpeled13/super-app:node
docker pull omerpeled13/super-app:php
docker pull omerpeled13/super-app:mysql

# Run the new Docker containers
docker run -d --name mysql-container -p 3306:3306 omerpeled13/super-app:mysql
docker run -d --name node-container -p 3000:3000 omerpeled13/super-app:node
docker run -d --name php-container -p 80:80 omerpeled13/super-app:php

