name: Build, Test, and Deploy to DockerHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create CodeDeploy Deployment
      run: |
        aws deploy create-deployment \
          --application-name peled-super-app \
          --deployment-group-name peled-super-app-dp \
          --revision "{\"revisionType\":\"GitHub\",\"gitHubLocation\":{\"repository\":\"omerpeled13/super-app\",\"commitId\":\"${{ github.sha }}\"}}"
